# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1453594914);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1453595034);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1453594554);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1453594794);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1453594674);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.slowStartup.averageTime", 9547);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150629114848");
user_pref("browser.startup.homepage_override.mstone", "39.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1453675449522");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1453589357714");
user_pref("datareporting.policy.firstRunTime", "1453589049522");
user_pref("datareporting.sessions.current.activeTicks", 58);
user_pref("datareporting.sessions.current.firstPaint", 9108);
user_pref("datareporting.sessions.current.main", 1234);
user_pref("datareporting.sessions.current.sessionRestored", 10281);
user_pref("datareporting.sessions.current.startTime", "1453594428620");
user_pref("datareporting.sessions.current.totalTime", 1357);
user_pref("datareporting.sessions.currentIndex", 6);
user_pref("datareporting.sessions.previous.0", "{\"s\":1453589045158,\"a\":6,\"t\":33,\"c\":false,\"m\":1363,\"fp\":8118,\"sr\":8532}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1453589337479,\"a\":5,\"t\":36,\"c\":false,\"m\":1545,\"fp\":9680,\"sr\":10164}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1453590212271,\"a\":5,\"t\":37,\"c\":false,\"m\":1385,\"fp\":10809,\"sr\":11186}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1453591090156,\"a\":4,\"t\":43,\"c\":false,\"m\":3181,\"fp\":17330,\"sr\":17827}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1453591880009,\"a\":5,\"t\":39,\"c\":false,\"m\":1314,\"fp\":11548,\"sr\":13540}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1453593397280,\"a\":6,\"t\":34,\"c\":false,\"m\":1393,\"fp\":8743,\"sr\":9259}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2014.08.06.beta,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1453594915);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "39.0");
user_pref("extensions.lastPlatformVersion", "39.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0\",\"st\":1438751793000,\"mt\":1435579394000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"43.0.4\",\"st\":1452128367000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"43.0.4\",\"st\":1452128367000}},\"app-system-share\":{\"webapps-team@lists.launchpad.net\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"e\":true,\"v\":\"3.0.2\",\"st\":1438751895000,\"mt\":1397665356000},\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1438751894000,\"mt\":1420839872000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"e\":true,\"v\":\"2014.08.06.beta\",\"st\":1438751894000,\"mt\":1407283796000}},\"app-system-local\":{\"online-accounts@lists.launchpad.net\":{\"d\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"e\":true,\"v\":\"0.5\",\"st\":1438751895000,\"mt\":1390969548000}}}");
user_pref("gecko.buildID", "20150629114848");
user_pref("gecko.mstone", "39.0");
user_pref("idle.lastDailyNotification", 1453595967);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1453594499);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20150629114848");
user_pref("media.gmp-manager.lastCheck", 1453594499);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1453594429);
user_pref("toolkit.telemetry.previousBuildID", "20150629114848");
